PicamError = {
	0 :"PicamError_None",
	4 :"PicamError_UnexpectedError",
	3 :"PicamError_UnexpectedNullPointer",
	35 :"PicamError_InvalidPointer",
	39 :"PicamError_InvalidCount",
	42 :"PicamError_InvalidOperation",
	43 :"PicamError_OperationCanceled",
	1 :"PicamError_LibraryNotInitialized",
	5 :"PicamError_LibraryAlreadyInitialized",
	16 :"PicamError_InvalidEnumeratedType",
	17 :"PicamError_EnumerationValueNotDefined",
	18 :"PicamError_NotDiscoveringCameras",
	19 :"PicamError_AlreadyDiscoveringCameras",
	48 :"PicamError_NotDiscoveringAccessories",
	49 :"PicamError_AlreadyDiscoveringAccessories",
	34 :"PicamError_NoCamerasAvailable",
	7 :"PicamError_CameraAlreadyOpened",
	8 :"PicamError_InvalidCameraID",
	45 :"PicamError_NoAccessoriesAvailable",
	46 :"PicamError_AccessoryAlreadyOpened",
	47 :"PicamError_InvalidAccessoryID",
	9 :"PicamError_InvalidHandle",
	15 :"PicamError_DeviceCommunicationFailed",
	23 :"PicamError_DeviceDisconnected",
	24 :"PicamError_DeviceOpenElsewhere",
	6 :"PicamError_InvalidDemoModel",
	21 :"PicamError_InvalidDemoSerialNumber",
	22 :"PicamError_DemoAlreadyConnected",
	40 :"PicamError_DemoNotSupported",
	11 :"PicamError_ParameterHasInvalidValueType",
	13 :"PicamError_ParameterHasInvalidConstraintType",
	12 :"PicamError_ParameterDoesNotExist",
	10 :"PicamError_ParameterValueIsReadOnly",
	2 :"PicamError_InvalidParameterValue",
	38 :"PicamError_InvalidConstraintCategory",
	14 :"PicamError_ParameterValueIsIrrelevant",
	25 :"PicamError_ParameterIsNotOnlineable",
	26 :"PicamError_ParameterIsNotReadable",
	50 :"PicamError_ParameterIsNotWaitableStatus",
	51 :"PicamError_InvalidWaitableStatusParameterTimeOut",
	28 :"PicamError_InvalidParameterValues",
	29 :"PicamError_ParametersNotCommitted",
	30 :"PicamError_InvalidAcquisitionBuffer",
	36 :"PicamError_InvalidReadoutCount",
	37 :"PicamError_InvalidReadoutTimeOut",
	31 :"PicamError_InsufficientMemory",
	20 :"PicamError_AcquisitionInProgress",
	27 :"PicamError_AcquisitionNotInProgress",
	32 :"PicamError_TimeOutOccurred",
	33 :"PicamError_AcquisitionUpdatedHandlerRegistered",
	44 :"PicamError_InvalidAcquisitionState",
	41 :"PicamError_NondestructiveReadoutEnabled",
	52 :"PicamError_ShutterOverheated",
	54 :"PicamError_CenterWavelengthFaulted",
	53 :"PicamError_CameraFaulted"
}

PicamEnumeratedType = {
	1 :"PicamEnumeratedType_Error",
	29 :"PicamEnumeratedType_EnumeratedType",
	2 :"PicamEnumeratedType_Model",
	3 :"PicamEnumeratedType_ComputerInterface",
	26 :"PicamEnumeratedType_DiscoveryAction",
	27 :"PicamEnumeratedType_HandleType",
	4 :"PicamEnumeratedType_ValueType",
	5 :"PicamEnumeratedType_ConstraintType",
	6 :"PicamEnumeratedType_Parameter",
	53 :"PicamEnumeratedType_ActiveShutter",
	7 :"PicamEnumeratedType_AdcAnalogGain",
	8 :"PicamEnumeratedType_AdcQuality",
	9 :"PicamEnumeratedType_CcdCharacteristicsMask",
	51 :"PicamEnumeratedType_CenterWavelengthStatus",
	56 :"PicamEnumeratedType_CoolingFanStatus",
	42 :"PicamEnumeratedType_EMIccdGainControlMode",
	36 :"PicamEnumeratedType_GateTrackingMask",
	34 :"PicamEnumeratedType_GatingMode",
	38 :"PicamEnumeratedType_GatingSpeed",
	48 :"PicamEnumeratedType_GratingCoating",
	49 :"PicamEnumeratedType_GratingType",
	35 :"PicamEnumeratedType_IntensifierOptionsMask",
	33 :"PicamEnumeratedType_IntensifierStatus",
	45 :"PicamEnumeratedType_LaserOutputMode",
	54 :"PicamEnumeratedType_LaserStatus",
	46 :"PicamEnumeratedType_LightSource",
	47 :"PicamEnumeratedType_LightSourceStatus",
	41 :"PicamEnumeratedType_ModulationTrackingMask",
	10 :"PicamEnumeratedType_OrientationMask",
	11 :"PicamEnumeratedType_OutputSignal",
	39 :"PicamEnumeratedType_PhosphorType",
	40 :"PicamEnumeratedType_PhotocathodeSensitivity",
	43 :"PicamEnumeratedType_PhotonDetectionMode",
	12 :"PicamEnumeratedType_PixelFormat",
	13 :"PicamEnumeratedType_ReadoutControlMode",
	14 :"PicamEnumeratedType_SensorTemperatureStatus",
	15 :"PicamEnumeratedType_SensorType",
	52 :"PicamEnumeratedType_ShutterStatus",
	16 :"PicamEnumeratedType_ShutterTimingMode",
	50 :"PicamEnumeratedType_ShutterType",
	17 :"PicamEnumeratedType_TimeStampsMask",
	30 :"PicamEnumeratedType_TriggerCoupling",
	18 :"PicamEnumeratedType_TriggerDetermination",
	19 :"PicamEnumeratedType_TriggerResponse",
	31 :"PicamEnumeratedType_TriggerSource",
	55 :"PicamEnumeratedType_TriggerStatus",
	32 :"PicamEnumeratedType_TriggerTermination",
	57 :"PicamEnumeratedType_VacuumStatus",
	20 :"PicamEnumeratedType_ValueAccess",
	28 :"PicamEnumeratedType_DynamicsMask",
	21 :"PicamEnumeratedType_ConstraintScope",
	22 :"PicamEnumeratedType_ConstraintSeverity",
	23 :"PicamEnumeratedType_ConstraintCategory",
	24 :"PicamEnumeratedType_RoisConstraintRulesMask",
	25 :"PicamEnumeratedType_AcquisitionErrorsMask",
	37 :"PicamEnumeratedType_AcquisitionState",
	44 :"PicamEnumeratedType_AcquisitionStateErrorsMask"
}

PicamModel = {
	1400 :"PicamModel_PIMteSeries",
	1401 :"PicamModel_PIMte1024Series",
	1402 :"PicamModel_PIMte1024F",
	1403 :"PicamModel_PIMte1024B",
	1405 :"PicamModel_PIMte1024BR",
	1404 :"PicamModel_PIMte1024BUV",
	1406 :"PicamModel_PIMte1024FTSeries",
	1407 :"PicamModel_PIMte1024FT",
	1408 :"PicamModel_PIMte1024BFT",
	1412 :"PicamModel_PIMte1300Series",
	1413 :"PicamModel_PIMte1300B",
	1414 :"PicamModel_PIMte1300R",
	1415 :"PicamModel_PIMte1300BR",
	1416 :"PicamModel_PIMte2048Series",
	1417 :"PicamModel_PIMte2048B",
	1418 :"PicamModel_PIMte2048BR",
	1409 :"PicamModel_PIMte2KSeries",
	1410 :"PicamModel_PIMte2KB",
	1411 :"PicamModel_PIMte2KBUV",
	2000 :"PicamModel_PIMte3Series",
	2001 :"PicamModel_PIMte32048Series",
	2002 :"PicamModel_PIMte32048B",
	0 :"PicamModel_PixisSeries",
	1 :"PicamModel_Pixis100Series",
	2 :"PicamModel_Pixis100F",
	6 :"PicamModel_Pixis100B",
	3 :"PicamModel_Pixis100R",
	4 :"PicamModel_Pixis100C",
	5 :"PicamModel_Pixis100BR",
	54 :"PicamModel_Pixis100BExcelon",
	55 :"PicamModel_Pixis100BRExcelon",
	7 :"PicamModel_PixisXO100B",
	8 :"PicamModel_PixisXO100BR",
	68 :"PicamModel_PixisXB100B",
	69 :"PicamModel_PixisXB100BR",
	26 :"PicamModel_Pixis256Series",
	27 :"PicamModel_Pixis256F",
	29 :"PicamModel_Pixis256B",
	28 :"PicamModel_Pixis256E",
	30 :"PicamModel_Pixis256BR",
	31 :"PicamModel_PixisXB256BR",
	37 :"PicamModel_Pixis400Series",
	38 :"PicamModel_Pixis400F",
	40 :"PicamModel_Pixis400B",
	39 :"PicamModel_Pixis400R",
	41 :"PicamModel_Pixis400BR",
	56 :"PicamModel_Pixis400BExcelon",
	57 :"PicamModel_Pixis400BRExcelon",
	42 :"PicamModel_PixisXO400B",
	70 :"PicamModel_PixisXB400BR",
	43 :"PicamModel_Pixis512Series",
	44 :"PicamModel_Pixis512F",
	45 :"PicamModel_Pixis512B",
	46 :"PicamModel_Pixis512BUV",
	58 :"PicamModel_Pixis512BExcelon",
	49 :"PicamModel_PixisXO512F",
	50 :"PicamModel_PixisXO512B",
	48 :"PicamModel_PixisXF512F",
	47 :"PicamModel_PixisXF512B",
	9 :"PicamModel_Pixis1024Series",
	10 :"PicamModel_Pixis1024F",
	11 :"PicamModel_Pixis1024B",
	13 :"PicamModel_Pixis1024BR",
	12 :"PicamModel_Pixis1024BUV",
	59 :"PicamModel_Pixis1024BExcelon",
	60 :"PicamModel_Pixis1024BRExcelon",
	16 :"PicamModel_PixisXO1024F",
	14 :"PicamModel_PixisXO1024B",
	15 :"PicamModel_PixisXO1024BR",
	17 :"PicamModel_PixisXF1024F",
	18 :"PicamModel_PixisXF1024B",
	71 :"PicamModel_PixisXB1024BR",
	51 :"PicamModel_Pixis1300Series",
	52 :"PicamModel_Pixis1300F",
	75 :"PicamModel_Pixis1300F_2",
	53 :"PicamModel_Pixis1300B",
	73 :"PicamModel_Pixis1300BR",
	61 :"PicamModel_Pixis1300BExcelon",
	62 :"PicamModel_Pixis1300BRExcelon",
	65 :"PicamModel_PixisXO1300B",
	66 :"PicamModel_PixisXF1300B",
	72 :"PicamModel_PixisXB1300R",
	20 :"PicamModel_Pixis2048Series",
	21 :"PicamModel_Pixis2048F",
	22 :"PicamModel_Pixis2048B",
	67 :"PicamModel_Pixis2048BR",
	63 :"PicamModel_Pixis2048BExcelon",
	74 :"PicamModel_Pixis2048BRExcelon",
	23 :"PicamModel_PixisXO2048B",
	25 :"PicamModel_PixisXF2048F",
	24 :"PicamModel_PixisXF2048B",
	32 :"PicamModel_Pixis2KSeries",
	33 :"PicamModel_Pixis2KF",
	34 :"PicamModel_Pixis2KB",
	36 :"PicamModel_Pixis2KBUV",
	64 :"PicamModel_Pixis2KBExcelon",
	35 :"PicamModel_PixisXO2KB",
	100 :"PicamModel_QuadroSeries",
	101 :"PicamModel_Quadro4096",
	103 :"PicamModel_Quadro4096_2",
	102 :"PicamModel_Quadro4320",
	200 :"PicamModel_ProEMSeries",
	203 :"PicamModel_ProEM512Series",
	201 :"PicamModel_ProEM512B",
	205 :"PicamModel_ProEM512BK",
	204 :"PicamModel_ProEM512BExcelon",
	206 :"PicamModel_ProEM512BKExcelon",
	207 :"PicamModel_ProEM1024Series",
	202 :"PicamModel_ProEM1024B",
	208 :"PicamModel_ProEM1024BExcelon",
	209 :"PicamModel_ProEM1600Series",
	212 :"PicamModel_ProEM1600xx2B",
	210 :"PicamModel_ProEM1600xx2BExcelon",
	213 :"PicamModel_ProEM1600xx4B",
	211 :"PicamModel_ProEM1600xx4BExcelon",
	600 :"PicamModel_ProEMPlusSeries",
	603 :"PicamModel_ProEMPlus512Series",
	601 :"PicamModel_ProEMPlus512B",
	605 :"PicamModel_ProEMPlus512BK",
	604 :"PicamModel_ProEMPlus512BExcelon",
	606 :"PicamModel_ProEMPlus512BKExcelon",
	607 :"PicamModel_ProEMPlus1024Series",
	602 :"PicamModel_ProEMPlus1024B",
	608 :"PicamModel_ProEMPlus1024BExcelon",
	609 :"PicamModel_ProEMPlus1600Series",
	612 :"PicamModel_ProEMPlus1600xx2B",
	610 :"PicamModel_ProEMPlus1600xx2BExcelon",
	613 :"PicamModel_ProEMPlus1600xx4B",
	611 :"PicamModel_ProEMPlus1600xx4BExcelon",
	1200 :"PicamModel_ProEMHSSeries",
	1201 :"PicamModel_ProEMHS512Series",
	1202 :"PicamModel_ProEMHS512B",
	1207 :"PicamModel_ProEMHS512BK",
	1203 :"PicamModel_ProEMHS512BExcelon",
	1208 :"PicamModel_ProEMHS512BKExcelon",
	1216 :"PicamModel_ProEMHS512B_2",
	1217 :"PicamModel_ProEMHS512BExcelon_2",
	1204 :"PicamModel_ProEMHS1024Series",
	1205 :"PicamModel_ProEMHS1024B",
	1206 :"PicamModel_ProEMHS1024BExcelon",
	1212 :"PicamModel_ProEMHS1024B_2",
	1213 :"PicamModel_ProEMHS1024BExcelon_2",
	1214 :"PicamModel_ProEMHS1024B_3",
	1215 :"PicamModel_ProEMHS1024BExcelon_3",
	1209 :"PicamModel_ProEMHS1K10Series",
	1210 :"PicamModel_ProEMHS1KB10",
	1211 :"PicamModel_ProEMHS1KB10Excelon",
	300 :"PicamModel_PIMax3Series",
	301 :"PicamModel_PIMax31024I",
	302 :"PicamModel_PIMax31024x256",
	700 :"PicamModel_PIMax4Series",
	703 :"PicamModel_PIMax41024ISeries",
	701 :"PicamModel_PIMax41024I",
	704 :"PicamModel_PIMax41024IRF",
	710 :"PicamModel_PIMax41024FSeries",
	711 :"PicamModel_PIMax41024F",
	712 :"PicamModel_PIMax41024FRF",
	705 :"PicamModel_PIMax41024x256Series",
	702 :"PicamModel_PIMax41024x256",
	706 :"PicamModel_PIMax41024x256RF",
	716 :"PicamModel_PIMax42048Series",
	717 :"PicamModel_PIMax42048F",
	718 :"PicamModel_PIMax42048B",
	719 :"PicamModel_PIMax42048FRF",
	720 :"PicamModel_PIMax42048BRF",
	708 :"PicamModel_PIMax4512EMSeries",
	707 :"PicamModel_PIMax4512EM",
	709 :"PicamModel_PIMax4512BEM",
	713 :"PicamModel_PIMax41024EMSeries",
	715 :"PicamModel_PIMax41024EM",
	714 :"PicamModel_PIMax41024BEM",
	400 :"PicamModel_PylonSeries",
	418 :"PicamModel_Pylon100Series",
	404 :"PicamModel_Pylon100F",
	401 :"PicamModel_Pylon100B",
	407 :"PicamModel_Pylon100BR",
	425 :"PicamModel_Pylon100BExcelon",
	426 :"PicamModel_Pylon100BRExcelon",
	419 :"PicamModel_Pylon256Series",
	409 :"PicamModel_Pylon256F",
	410 :"PicamModel_Pylon256B",
	411 :"PicamModel_Pylon256E",
	412 :"PicamModel_Pylon256BR",
	420 :"PicamModel_Pylon400Series",
	405 :"PicamModel_Pylon400F",
	402 :"PicamModel_Pylon400B",
	408 :"PicamModel_Pylon400BR",
	427 :"PicamModel_Pylon400BExcelon",
	428 :"PicamModel_Pylon400BRExcelon",
	421 :"PicamModel_Pylon1024Series",
	417 :"PicamModel_Pylon1024B",
	429 :"PicamModel_Pylon1024BExcelon",
	422 :"PicamModel_Pylon1300Series",
	406 :"PicamModel_Pylon1300F",
	403 :"PicamModel_Pylon1300B",
	438 :"PicamModel_Pylon1300R",
	432 :"PicamModel_Pylon1300BR",
	430 :"PicamModel_Pylon1300BExcelon",
	433 :"PicamModel_Pylon1300BRExcelon",
	423 :"PicamModel_Pylon2048Series",
	415 :"PicamModel_Pylon2048F",
	434 :"PicamModel_Pylon2048B",
	416 :"PicamModel_Pylon2048BR",
	435 :"PicamModel_Pylon2048BExcelon",
	436 :"PicamModel_Pylon2048BRExcelon",
	424 :"PicamModel_Pylon2KSeries",
	413 :"PicamModel_Pylon2KF",
	414 :"PicamModel_Pylon2KB",
	437 :"PicamModel_Pylon2KBUV",
	431 :"PicamModel_Pylon2KBExcelon",
	900 :"PicamModel_PylonirSeries",
	901 :"PicamModel_Pylonir1024Series",
	902 :"PicamModel_Pylonir102422",
	903 :"PicamModel_Pylonir102417",
	500 :"PicamModel_PionirSeries",
	501 :"PicamModel_Pionir640",
	800 :"PicamModel_NirvanaSeries",
	801 :"PicamModel_Nirvana640",
	1300 :"PicamModel_NirvanaSTSeries",
	1301 :"PicamModel_NirvanaST640",
	1100 :"PicamModel_NirvanaLNSeries",
	1101 :"PicamModel_NirvanaLN640",
	1800 :"PicamModel_SophiaSeries",
	1801 :"PicamModel_Sophia2048Series",
	1802 :"PicamModel_Sophia2048B",
	1803 :"PicamModel_Sophia2048BExcelon",
	1804 :"PicamModel_SophiaXO2048B",
	1805 :"PicamModel_SophiaXF2048B",
	1806 :"PicamModel_SophiaXB2048B",
	1807 :"PicamModel_Sophia2048135Series",
	1808 :"PicamModel_Sophia2048135",
	1809 :"PicamModel_Sophia2048B135",
	1810 :"PicamModel_Sophia2048BR135",
	1811 :"PicamModel_Sophia2048B135Excelon",
	1812 :"PicamModel_Sophia2048BR135Excelon",
	1813 :"PicamModel_SophiaXO2048B135",
	1814 :"PicamModel_SophiaXO2048BR135",
	1500 :"PicamModel_BlazeSeries",
	1507 :"PicamModel_Blaze100Series",
	1501 :"PicamModel_Blaze100B",
	1505 :"PicamModel_Blaze100BR",
	1503 :"PicamModel_Blaze100HR",
	1509 :"PicamModel_Blaze100BRLD",
	1511 :"PicamModel_Blaze100BExcelon",
	1513 :"PicamModel_Blaze100BRExcelon",
	1515 :"PicamModel_Blaze100HRExcelon",
	1517 :"PicamModel_Blaze100BRLDExcelon",
	1508 :"PicamModel_Blaze400Series",
	1502 :"PicamModel_Blaze400B",
	1506 :"PicamModel_Blaze400BR",
	1504 :"PicamModel_Blaze400HR",
	1510 :"PicamModel_Blaze400BRLD",
	1512 :"PicamModel_Blaze400BExcelon",
	1514 :"PicamModel_Blaze400BRExcelon",
	1516 :"PicamModel_Blaze400HRExcelon",
	1518 :"PicamModel_Blaze400BRLDExcelon",
	1600 :"PicamModel_FergieSeries",
	1601 :"PicamModel_Fergie256Series",
	1602 :"PicamModel_Fergie256B",
	1607 :"PicamModel_Fergie256BR",
	1603 :"PicamModel_Fergie256BExcelon",
	1608 :"PicamModel_Fergie256BRExcelon",
	1604 :"PicamModel_Fergie256FTSeries",
	1609 :"PicamModel_Fergie256FFT",
	1605 :"PicamModel_Fergie256BFT",
	1610 :"PicamModel_Fergie256BRFT",
	1606 :"PicamModel_Fergie256BFTExcelon",
	1611 :"PicamModel_Fergie256BRFTExcelon",
	1700 :"PicamModel_FergieAccessorySeries",
	1701 :"PicamModel_FergieLampSeries",
	1702 :"PicamModel_FergieAEL",
	1703 :"PicamModel_FergieQTH",
	1704 :"PicamModel_FergieLaserSeries",
	1705 :"PicamModel_FergieLaser785",
	1900 :"PicamModel_KuroSeries",
	1901 :"PicamModel_Kuro1200B",
	1902 :"PicamModel_Kuro1608B",
	1903 :"PicamModel_Kuro2048B"
}

PicamComputerInterface = {
	1 :"PicamComputerInterface_Usb2",
	2 :"PicamComputerInterface_1394A",
	3 :"PicamComputerInterface_GigabitEthernet",
	4 :"PicamComputerInterface_Usb3",
}

PicamStringSize = {
	64 :"PicamStringSize_SensorName",
	64 :"PicamStringSize_SerialNumber",
	64 :"PicamStringSize_FirmwareName",
	256 :"PicamStringSize_FirmwareDetail",
}

PicamValueType = {
	1 :"PicamValueType_Integer",
	3 :"PicamValueType_Boolean",
	4 :"PicamValueType_Enumeration",
	6 :"PicamValueType_LargeInteger",
	2 :"PicamValueType_FloatingPoint",
	5 :"PicamValueType_Rois",
	7 :"PicamValueType_Pulse",
	8 :"PicamValueType_Modulations",
}

PicamConstraintType = {
	1 :"PicamConstraintType_None",
	2 :"PicamConstraintType_Range",
	3 :"PicamConstraintType_Collection",
	4 :"PicamConstraintType_Rois",
	5 :"PicamConstraintType_Pulse",
	6 :"PicamConstraintType_Modulations",
}

# PicamParameter = {
# 	PI_V(FloatingPointRange23) :"PicamParameter_ExposureTime",
# 	PI_V(EnumerationCollection24) :"PicamParameter_ShutterTimingMode",
# 	PI_V(FloatingPointRange46) :"PicamParameter_ShutterOpeningDelay",
# 	PI_V(FloatingPointRange25) :"PicamParameter_ShutterClosingDelay",
# 	PI_V(FloatingPointCollection47) :"PicamParameter_ShutterDelayResolution",
# 	PI_V(EnumerationNone139) :"PicamParameter_InternalShutterType",
# 	PI_V(EnumerationNone153) :"PicamParameter_InternalShutterStatus",
# 	PI_V(EnumerationNone152) :"PicamParameter_ExternalShutterType",
# 	PI_V(EnumerationNone154) :"PicamParameter_ExternalShutterStatus",
# 	PI_V(EnumerationCollection155) :"PicamParameter_ActiveShutter",
# 	PI_V(EnumerationNone156) :"PicamParameter_InactiveShutterTimingModeResult",
# 	PI_V(EnumerationCollection93) :"PicamParameter_GatingMode",
# 	PI_V(PulsePulse94) :"PicamParameter_RepetitiveGate",
# 	PI_V(PulsePulse95) :"PicamParameter_SequentialStartingGate",
# 	PI_V(PulsePulse96) :"PicamParameter_SequentialEndingGate",
# 	PI_V(LargeIntegerRange97) :"PicamParameter_SequentialGateStepCount",
# 	PI_V(LargeIntegerRange98) :"PicamParameter_SequentialGateStepIterations",
# 	PI_V(PulsePulse102) :"PicamParameter_DifStartingGate",
# 	PI_V(PulsePulse103) :"PicamParameter_DifEndingGate",
# 	PI_V(BooleanCollection86) :"PicamParameter_EnableIntensifier",
# 	PI_V(EnumerationNone87) :"PicamParameter_IntensifierStatus",
# 	PI_V(IntegerRange88) :"PicamParameter_IntensifierGain",
# 	PI_V(EnumerationCollection123) :"PicamParameter_EMIccdGainControlMode",
# 	PI_V(IntegerRange124) :"PicamParameter_EMIccdGain",
# 	PI_V(FloatingPointRange89) :"PicamParameter_PhosphorDecayDelay",
# 	PI_V(FloatingPointCollection90) :"PicamParameter_PhosphorDecayDelayResolution",
# 	PI_V(BooleanCollection100) :"PicamParameter_BracketGating",
# 	PI_V(EnumerationNone101) :"PicamParameter_IntensifierOptions",
# 	PI_V(BooleanCollection111) :"PicamParameter_EnableModulation",
# 	PI_V(FloatingPointRange118) :"PicamParameter_ModulationDuration",
# 	PI_V(FloatingPointRange112) :"PicamParameter_ModulationFrequency",
# 	PI_V(FloatingPointRange113) :"PicamParameter_RepetitiveModulationPhase",
# 	PI_V(FloatingPointRange114) :"PicamParameter_SequentialStartingModulationPhase",
# 	PI_V(FloatingPointRange115) :"PicamParameter_SequentialEndingModulationPhase",
# 	PI_V(ModulationsModulations119) :"PicamParameter_CustomModulationSequence",
# 	PI_V(EnumerationNone107) :"PicamParameter_PhotocathodeSensitivity",
# 	PI_V(EnumerationNone108) :"PicamParameter_GatingSpeed",
# 	PI_V(EnumerationNone109) :"PicamParameter_PhosphorType",
# 	PI_V(FloatingPointNone110) :"PicamParameter_IntensifierDiameter",
# 	PI_V(FloatingPointCollection33) :"PicamParameter_AdcSpeed",
# 	PI_V(IntegerCollection34) :"PicamParameter_AdcBitDepth",
# 	PI_V(EnumerationCollection35) :"PicamParameter_AdcAnalogGain",
# 	PI_V(EnumerationCollection36) :"PicamParameter_AdcQuality",
# 	PI_V(IntegerRange53) :"PicamParameter_AdcEMGain",
# 	PI_V(BooleanCollection106) :"PicamParameter_CorrectPixelBias",
# 	PI_V(EnumerationCollection79) :"PicamParameter_TriggerSource",
# 	PI_V(EnumerationCollection30) :"PicamParameter_TriggerResponse",
# 	PI_V(EnumerationCollection31) :"PicamParameter_TriggerDetermination",
# 	PI_V(FloatingPointRange80) :"PicamParameter_TriggerFrequency",
# 	PI_V(EnumerationCollection81) :"PicamParameter_TriggerTermination",
# 	PI_V(EnumerationCollection82) :"PicamParameter_TriggerCoupling",
# 	PI_V(FloatingPointRange83) :"PicamParameter_TriggerThreshold",
# 	PI_V(FloatingPointRange164) :"PicamParameter_TriggerDelay",
# 	PI_V(EnumerationCollection32) :"PicamParameter_OutputSignal",
# 	PI_V(BooleanCollection52) :"PicamParameter_InvertOutputSignal",
# 	PI_V(EnumerationCollection150) :"PicamParameter_OutputSignal2",
# 	PI_V(BooleanCollection151) :"PicamParameter_InvertOutputSignal2",
# 	PI_V(BooleanCollection161) :"PicamParameter_EnableAuxOutput",
# 	PI_V(PulsePulse91) :"PicamParameter_AuxOutput",
# 	PI_V(BooleanCollection84) :"PicamParameter_EnableSyncMaster",
# 	PI_V(FloatingPointRange85) :"PicamParameter_SyncMaster2Delay",
# 	PI_V(BooleanCollection116) :"PicamParameter_EnableModulationOutputSignal",
# 	PI_V(FloatingPointRange117) :"PicamParameter_ModulationOutputSignalFrequency",
# 	PI_V(FloatingPointRange120) :"PicamParameter_ModulationOutputSignalAmplitude",
# 	PI_V(BooleanCollection131) :"PicamParameter_AnticipateTrigger",
# 	PI_V(FloatingPointRange132) :"PicamParameter_DelayFromPreTrigger",
# 	PI_V(EnumerationCollection26) :"PicamParameter_ReadoutControlMode",
# 	PI_V(FloatingPointNone27) :"PicamParameter_ReadoutTimeCalculation",
# 	PI_V(IntegerCollection28) :"PicamParameter_ReadoutPortCount",
# 	PI_V(EnumerationNone54) :"PicamParameter_ReadoutOrientation",
# 	PI_V(IntegerRange56) :"PicamParameter_KineticsWindowHeight",
# 	PI_V(IntegerRange163) :"PicamParameter_SeNsRWindowHeight",
# 	PI_V(FloatingPointCollection13) :"PicamParameter_VerticalShiftRate",
# 	PI_V(LargeIntegerRange92) :"PicamParameter_Accumulations",
# 	PI_V(BooleanCollection128) :"PicamParameter_EnableNondestructiveReadout",
# 	PI_V(FloatingPointRange129) :"PicamParameter_NondestructiveReadoutPeriod",
# 	PI_V(RoisRois37) :"PicamParameter_Rois",
# 	PI_V(BooleanCollection39) :"PicamParameter_NormalizeOrientation",
# 	PI_V(BooleanCollection55) :"PicamParameter_DisableDataFormatting",
# 	PI_V(LargeIntegerRange40) :"PicamParameter_ReadoutCount",
# 	PI_V(LargeIntegerNone77) :"PicamParameter_ExactReadoutCountMaximum",
# 	PI_V(EnumerationCollection125) :"PicamParameter_PhotonDetectionMode",
# 	PI_V(FloatingPointRange126) :"PicamParameter_PhotonDetectionThreshold",
# 	PI_V(EnumerationCollection41) :"PicamParameter_PixelFormat",
# 	PI_V(IntegerNone42) :"PicamParameter_FrameSize",
# 	PI_V(IntegerNone43) :"PicamParameter_FrameStride",
# 	PI_V(IntegerNone44) :"PicamParameter_FramesPerReadout",
# 	PI_V(IntegerNone45) :"PicamParameter_ReadoutStride",
# 	PI_V(IntegerNone48) :"PicamParameter_PixelBitDepth",
# 	PI_V(FloatingPointNone50) :"PicamParameter_ReadoutRateCalculation",
# 	PI_V(FloatingPointNone99) :"PicamParameter_OnlineReadoutRateCalculation",
# 	PI_V(FloatingPointNone51) :"PicamParameter_FrameRateCalculation",
# 	PI_V(EnumerationNone38) :"PicamParameter_Orientation",
# 	PI_V(EnumerationCollection68) :"PicamParameter_TimeStamps",
# 	PI_V(LargeIntegerCollection69) :"PicamParameter_TimeStampResolution",
# 	PI_V(IntegerCollection70) :"PicamParameter_TimeStampBitDepth",
# 	PI_V(BooleanCollection71) :"PicamParameter_TrackFrames",
# 	PI_V(IntegerCollection72) :"PicamParameter_FrameTrackingBitDepth",
# 	PI_V(EnumerationCollection104) :"PicamParameter_GateTracking",
# 	PI_V(IntegerCollection105) :"PicamParameter_GateTrackingBitDepth",
# 	PI_V(EnumerationCollection121) :"PicamParameter_ModulationTracking",
# 	PI_V(IntegerCollection122) :"PicamParameter_ModulationTrackingBitDepth",
# 	PI_V(EnumerationNone57) :"PicamParameter_SensorType",
# 	PI_V(EnumerationNone58) :"PicamParameter_CcdCharacteristics",
# 	PI_V(IntegerNone59) :"PicamParameter_SensorActiveWidth",
# 	PI_V(IntegerNone60) :"PicamParameter_SensorActiveHeight",
# 	PI_V(IntegerNone159) :"PicamParameter_SensorActiveExtendedHeight",
# 	PI_V(IntegerNone61) :"PicamParameter_SensorActiveLeftMargin",
# 	PI_V(IntegerNone62) :"PicamParameter_SensorActiveTopMargin",
# 	PI_V(IntegerNone63) :"PicamParameter_SensorActiveRightMargin",
# 	PI_V(IntegerNone64) :"PicamParameter_SensorActiveBottomMargin",
# 	PI_V(IntegerNone65) :"PicamParameter_SensorMaskedHeight",
# 	PI_V(IntegerNone66) :"PicamParameter_SensorMaskedTopMargin",
# 	PI_V(IntegerNone67) :"PicamParameter_SensorMaskedBottomMargin",
# 	PI_V(IntegerNone49) :"PicamParameter_SensorSecondaryMaskedHeight",
# 	PI_V(IntegerNone74) :"PicamParameter_SensorSecondaryActiveHeight",
# 	PI_V(FloatingPointNone9) :"PicamParameter_PixelWidth",
# 	PI_V(FloatingPointNone10) :"PicamParameter_PixelHeight",
# 	PI_V(FloatingPointNone11) :"PicamParameter_PixelGapWidth",
# 	PI_V(FloatingPointNone12) :"PicamParameter_PixelGapHeight",
# 	PI_V(IntegerRange1) :"PicamParameter_ActiveWidth",
# 	PI_V(IntegerRange2) :"PicamParameter_ActiveHeight",
# 	PI_V(IntegerRange160) :"PicamParameter_ActiveExtendedHeight",
# 	PI_V(IntegerRange3) :"PicamParameter_ActiveLeftMargin",
# 	PI_V(IntegerRange4) :"PicamParameter_ActiveTopMargin",
# 	PI_V(IntegerRange5) :"PicamParameter_ActiveRightMargin",
# 	PI_V(IntegerRange6) :"PicamParameter_ActiveBottomMargin",
# 	PI_V(IntegerRange7) :"PicamParameter_MaskedHeight",
# 	PI_V(IntegerRange8) :"PicamParameter_MaskedTopMargin",
# 	PI_V(IntegerRange73) :"PicamParameter_MaskedBottomMargin",
# 	PI_V(IntegerRange75) :"PicamParameter_SecondaryMaskedHeight",
# 	PI_V(IntegerRange76) :"PicamParameter_SecondaryActiveHeight",
# 	PI_V(IntegerRange17) :"PicamParameter_CleanSectionFinalHeight",
# 	PI_V(IntegerRange18) :"PicamParameter_CleanSectionFinalHeightCount",
# 	PI_V(BooleanCollection19) :"PicamParameter_CleanSerialRegister",
# 	PI_V(IntegerRange20) :"PicamParameter_CleanCycleCount",
# 	PI_V(IntegerRange21) :"PicamParameter_CleanCycleHeight",
# 	PI_V(BooleanCollection78) :"PicamParameter_CleanBeforeExposure",
# 	PI_V(BooleanCollection22) :"PicamParameter_CleanUntilTrigger",
# 	PI_V(BooleanCollection130) :"PicamParameter_StopCleaningOnPreTrigger",
# 	PI_V(FloatingPointRange14) :"PicamParameter_SensorTemperatureSetPoint",
# 	PI_V(FloatingPointNone15) :"PicamParameter_SensorTemperatureReading",
# 	PI_V(EnumerationNone16) :"PicamParameter_SensorTemperatureStatus",
# 	PI_V(BooleanCollection29) :"PicamParameter_DisableCoolingFan",
# 	PI_V(EnumerationNone162) :"PicamParameter_CoolingFanStatus",
# 	PI_V(BooleanCollection127) :"PicamParameter_EnableSensorWindowHeater",
# 	PI_V(EnumerationNone165) :"PicamParameter_VacuumStatus",
# 	PI_V(FloatingPointRange140) :"PicamParameter_CenterWavelengthSetPoint",
# 	PI_V(FloatingPointNone141) :"PicamParameter_CenterWavelengthReading",
# 	PI_V(EnumerationNone149) :"PicamParameter_CenterWavelengthStatus",
# 	PI_V(EnumerationNone142) :"PicamParameter_GratingType",
# 	PI_V(EnumerationNone143) :"PicamParameter_GratingCoating",
# 	PI_V(FloatingPointNone144) :"PicamParameter_GratingGrooveDensity",
# 	PI_V(FloatingPointNone145) :"PicamParameter_GratingBlazingWavelength",
# 	PI_V(FloatingPointNone146) :"PicamParameter_FocalLength",
# 	PI_V(FloatingPointNone147) :"PicamParameter_InclusionAngle",
# 	PI_V(FloatingPointNone148) :"PicamParameter_SensorAngle",
# 	PI_V(EnumerationCollection133) :"PicamParameter_LightSource",
# 	PI_V(EnumerationNone134) :"PicamParameter_LightSourceStatus",
# 	PI_V(FloatingPointNone135) :"PicamParameter_Age",
# 	PI_V(FloatingPointNone136) :"PicamParameter_LifeExpectancy",
# 	PI_V(EnumerationCollection137) :"PicamParameter_LaserOutputMode",
# 	PI_V(FloatingPointRange138) :"PicamParameter_LaserPower",
# 	PI_V(EnumerationNone157) :"PicamParameter_LaserStatus",
# 	PI_V(EnumerationNone158) :"PicamParameter_InputTriggerStatus"
# }

PicamActiveShutter = {
	1 :"PicamActiveShutter_None",
	2 :"PicamActiveShutter_Internal",
	3 :"PicamActiveShutter_External"
}

PicamAdcAnalogGain ={
	1 :"PicamAdcAnalogGain_Low",
	2 :"PicamAdcAnalogGain_Medium",
	3 :"PicamAdcAnalogGain_High"
}

PicamAdcQuality = {
	1 :"PicamAdcQuality_LowNoise",
	2 :"PicamAdcQuality_HighCapacity",
	4 :"PicamAdcQuality_HighSpeed",
	3 :"PicamAdcQuality_ElectronMultiplied"
}

PicamCcdCharacteristicsMask = {
	0x000 :"PicamCcdCharacteristicsMask_None",
	0x001 :"PicamCcdCharacteristicsMask_BackIlluminated",
	0x002 :"PicamCcdCharacteristicsMask_DeepDepleted",
	0x004 :"PicamCcdCharacteristicsMask_OpenElectrode",
	0x008 :"PicamCcdCharacteristicsMask_UVEnhanced",
	0x010 :"PicamCcdCharacteristicsMask_ExcelonEnabled",
	0x020 :"PicamCcdCharacteristicsMask_SecondaryMask",
	0x040 :"PicamCcdCharacteristicsMask_Multiport",
	0x080 :"PicamCcdCharacteristicsMask_AdvancedInvertedMode",
	0x100 :"PicamCcdCharacteristicsMask_HighResistivity"
}

PicamCenterWavelengthStatus = {
	1 :"PicamCenterWavelengthStatus_Moving",
	2 :"PicamCenterWavelengthStatus_Stationary",
	3 :"PicamCenterWavelengthStatus_Faulted"
}

PicamCoolingFanStatus = {
	1 :"PicamCoolingFanStatus_Off",
	2 :"PicamCoolingFanStatus_On",
	3 :"PicamCoolingFanStatus_ForcedOn"
}

PicamEMIccdGainControlMode = {
	1 :"PicamEMIccdGainControlMode_Optimal",
	2 :"PicamEMIccdGainControlMode_Manual"
}

PicamGateTrackingMask = {
	0x0 :"PicamGateTrackingMask_None",
	0x1 :"PicamGateTrackingMask_Delay",
	0x2 :"PicamGateTrackingMask_Width"
}

PicamGatingMode = {
	4 :"PicamGatingMode_Disabled",
	1 :"PicamGatingMode_Repetitive",
	2 :"PicamGatingMode_Sequential",
	3 :"PicamGatingMode_Custom"
}

PicamGatingSpeed = {
	1 :"PicamGatingSpeed_Fast",
	2 :"PicamGatingSpeed_Slow"
}

PicamGratingCoating = {
	1 :"PicamGratingCoating_Al",
	4 :"PicamGratingCoating_AlMgF2",
	2 :"PicamGratingCoating_Ag",
	3 :"PicamGratingCoating_Au"
}

PicamGratingType = {
	1 :"PicamGratingType_Ruled",
	2 :"PicamGratingType_HolographicVisible",
	3 :"PicamGratingType_HolographicNir",
	4 :"PicamGratingType_HolographicUV",
	5 :"PicamGratingType_Mirror"
}

PicamIntensifierOptionsMask = {
	0x0 :"PicamIntensifierOptionsMask_None",
	0x1 :"PicamIntensifierOptionsMask_McpGating",
	0x2 :"PicamIntensifierOptionsMask_SubNanosecondGating",
	0x4 :"PicamIntensifierOptionsMask_Modulation",
}

PicamIntensifierStatus = {
	1 :"PicamIntensifierStatus_PoweredOff",
	2 :"PicamIntensifierStatus_PoweredOn",
}

PicamLaserOutputMode = {
	1 :"PicamLaserOutputMode_Disabled",
	2 :"PicamLaserOutputMode_ContinuousWave",
	3 :"PicamLaserOutputMode_Pulsed",
}
PicamLaserStatus = {
	1 :"PicamLaserStatus_Disarmed",
	2 :"PicamLaserStatus_Unarmed",
	3 :"PicamLaserStatus_Arming",
	4 :"PicamLaserStatus_Armed",
}
PicamLightSource = {
	1 :"PicamLightSource_Disabled",
	2 :"PicamLightSource_Hg",
	3 :"PicamLightSource_NeAr",
	4 :"PicamLightSource_Qth",
}

LightSourceStatus = {
	1 :"PicamLightSourceStatus_Unstable",
	2 :"PicamLightSourceStatus_Stable",
}

PicamModulationTrackingMask = {
	0x0 :"PicamModulationTrackingMask_None",
	0x1 :"PicamModulationTrackingMask_Duration",
	0x2 :"PicamModulationTrackingMask_Frequency",
	0x4 :"PicamModulationTrackingMask_Phase",
	0x8 :"PicamModulationTrackingMask_OutputSignalFrequency",
}

PicamOrientationMask = {
	0x0 :"PicamOrientationMask_Normal",
	0x1 :"PicamOrientationMask_FlippedHorizontally",
	0x2 :"PicamOrientationMask_FlippedVertically",
}

PicamOutputSignal = {
	6 :"PicamOutputSignal_Acquiring",
	5 :"PicamOutputSignal_AlwaysHigh",
	4 :"PicamOutputSignal_AlwaysLow",
	14 :"PicamOutputSignal_AuxOutput",
	3 :"PicamOutputSignal_Busy",
	9 :"PicamOutputSignal_EffectivelyExposing",
	15 :"PicamOutputSignal_EffectivelyExposingAlternation",
	8 :"PicamOutputSignal_Exposing",
	13 :"PicamOutputSignal_Gate",
	12 :"PicamOutputSignal_InternalTriggerT0",
	1 :"PicamOutputSignal_NotReadingOut",
	10 :"PicamOutputSignal_ReadingOut",
	7 :"PicamOutputSignal_ShiftingUnderMask",
	2 :"PicamOutputSignal_ShutterOpen",
	11 :"PicamOutputSignal_WaitingForTrigger",
}

PicamPhosphorType = {
	1 :"PicamPhosphorType_P43",
	2 :"PicamPhosphorType_P46",
}
PicamPhotocathodeSensitivity = {
	1 :"PicamPhotocathodeSensitivity_RedBlue",
	7 :"PicamPhotocathodeSensitivity_SuperRed",
	2 :"PicamPhotocathodeSensitivity_SuperBlue",
	3 :"PicamPhotocathodeSensitivity_UV",
	10 :"PicamPhotocathodeSensitivity_SolarBlind",
	4 :"PicamPhotocathodeSensitivity_Unigen2Filmless",
	9 :"PicamPhotocathodeSensitivity_InGaAsFilmless",
	5 :"PicamPhotocathodeSensitivity_HighQEFilmless",
	8 :"PicamPhotocathodeSensitivity_HighRedFilmless",
	6 :"PicamPhotocathodeSensitivity_HighBlueFilmless",
}
PicamPhotonDetectionMode = {
	1 :"PicamPhotonDetectionMode_Disabled",
	2 :"PicamPhotonDetectionMode_Thresholding",
	3 :"PicamPhotonDetectionMode_Clipping",
}
PicamPixelFormat = {
	1 :"PicamPixelFormat_Monochrome16Bit",
	2 :"PicamPixelFormat_Monochrome32Bit",
}
PicamReadoutControlMode = {
	1 :"PicamReadoutControlMode_FullFrame",
	2 :"PicamReadoutControlMode_FrameTransfer",
	5 :"PicamReadoutControlMode_Interline",
	8 :"PicamReadoutControlMode_RollingShutter",
	3 :"PicamReadoutControlMode_Kinetics",
	4 :"PicamReadoutControlMode_SpectraKinetics",
	6 :"PicamReadoutControlMode_Dif",
	7 :"PicamReadoutControlMode_SeNsR",
}
PicamSensorTemperatureStatus = {
	1 :"PicamSensorTemperatureStatus_Unlocked",
	2 :"PicamSensorTemperatureStatus_Locked",
	3 :"PicamSensorTemperatureStatus_Faulted",
}
PicamSensorType = {
	1 :"PicamSensorType_Ccd",
	2 :"PicamSensorType_InGaAs",
	3 :"PicamSensorType_Cmos",
}
PicamShutterStatus = {
	1 :"PicamShutterStatus_NotConnected",
	2 :"PicamShutterStatus_Connected",
	3 :"PicamShutterStatus_Overheated",
}
PicamShutterTimingMode = {
	1 :"PicamShutterTimingMode_Normal",
	2 :"PicamShutterTimingMode_AlwaysClosed",
	3 :"PicamShutterTimingMode_AlwaysOpen",
	4 :"PicamShutterTimingMode_OpenBeforeTrigger",
}
PicamShutterType = {
	1 :"PicamShutterType_None",
	2 :"PicamShutterType_VincentCS25",
	3 :"PicamShutterType_VincentCS45",
	9 :"PicamShutterType_VincentCS90",
	8 :"PicamShutterType_VincentDSS10",
	4 :"PicamShutterType_VincentVS25",
	5 :"PicamShutterType_VincentVS35",
	6 :"PicamShutterType_ProntorMagnetic0",
	7 :"PicamShutterType_ProntorMagneticE40",
}
PicamTimeStampsMask = {
	0x0 :"PicamTimeStampsMask_None",
	0x1 :"PicamTimeStampsMask_ExposureStarted",
	0x2 :"PicamTimeStampsMask_ExposureEnded",
}
PicamTriggerCoupling = {
	1 :"PicamTriggerCoupling_AC",
	2 :"PicamTriggerCoupling_DC",
}
PicamTriggerDetermination = {
	1 :"PicamTriggerDetermination_PositivePolarity",
	2 :"PicamTriggerDetermination_NegativePolarity",
	3 :"PicamTriggerDetermination_RisingEdge",
	4 :"PicamTriggerDetermination_FallingEdge",
	5 :"PicamTriggerDetermination_AlternatingEdgeRising",
	6 :"PicamTriggerDetermination_AlternatingEdgeFalling",
}

PicamTriggerResponse = {
	1 :"PicamTriggerResponse_NoResponse",
	5 :"PicamTriggerResponse_StartOnSingleTrigger",
	2 :"PicamTriggerResponse_ReadoutPerTrigger",
	3 :"PicamTriggerResponse_ShiftPerTrigger",
	6 :"PicamTriggerResponse_GatePerTrigger",
	4 :"PicamTriggerResponse_ExposeDuringTriggerPulse",
}

PicamTriggerSource = {
	3 :"PicamTriggerSource_None",
	2 :"PicamTriggerSource_Internal",
	1 :"PicamTriggerSource_External",
}

PicamTriggerStatus = {
	1 :"PicamTriggerStatus_NotConnected",
	2 :"PicamTriggerStatus_Connected",
}

PicamTriggerTermination = {
	1 :"PicamTriggerTermination_FiftyOhms",
	2 :"PicamTriggerTermination_HighImpedance",
}

PicamVacuumStatus = {
	1 :"PicamVacuumStatus_Sufficient",
	2 :"PicamVacuumStatus_Low",
}
typedefenumPicamValueAccess = {
	1 :"PicamValueAccess_ReadOnly",
	3 :"PicamValueAccess_ReadWriteTrivial",
	2 :"PicamValueAccess_ReadWrite",
}

PicamConstraintScope ={
	1 :"PicamConstraintScope_Independent",
	2 :"PicamConstraintScope_Dependent",
}
PicamConstraintSeverity = {
	1 :"PicamConstraintSeverity_Error",
	2 :"PicamConstraintSeverity_Warning",
}

PicamConstraintCategory = {
	1 :"PicamConstraintCategory_Capable",
	2 :"PicamConstraintCategory_Required",
	3 :"PicamConstraintCategory_Recommended",
}

PicamRoisConstraintRulesMask ={
	0x00 :"PicamRoisConstraintRulesMask_None",
	0x01 :"PicamRoisConstraintRulesMask_XBinningAlignment",
	0x02 :"PicamRoisConstraintRulesMask_YBinningAlignment",
	0x04 :"PicamRoisConstraintRulesMask_HorizontalSymmetry",
	0x08 :"PicamRoisConstraintRulesMask_VerticalSymmetry",
	0x10 :"PicamRoisConstraintRulesMask_SymmetryBoundsBinning",
}
PicamAcquisitionErrorsMask = {
	0x00 :"PicamAcquisitionErrorsMask_None",
	0x10 :"PicamAcquisitionErrorsMask_CameraFaulted",
	0x02 :"PicamAcquisitionErrorsMask_ConnectionLost",
	0x08 :"PicamAcquisitionErrorsMask_ShutterOverheated",
	0x01 :"PicamAcquisitionErrorsMask_DataLost",
	0x04 :"PicamAcquisitionErrorsMask_DataNotArriving",
}
